Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2024-10, with the labels that each got.

#86 [fix/#85-default-value] Default Value 설정 방식 변경
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/TagAlarm.java
  src/main/java/com/apps/pochak/block/domain/Block.java
  src/main/java/com/apps/pochak/comment/domain/Comment.java
  src/main/java/com/apps/pochak/follow/domain/Follow.java
  src/main/java/com/apps/pochak/global/BaseEntity.java
  src/main/java/com/apps/pochak/like/domain/LikeEntity.java
  src/main/java/com/apps/pochak/member/domain/Member.java
  src/main/java/com/apps/pochak/post/domain/Post.java
  src/main/java/com/apps/pochak/report/domain/Report.java
  src/main/java/com/apps/pochak/tag/domain/Tag.java
Labels: ⛏️ fix, 🔧 refactor

#82 [refactor/#67-find-by-id] `findByIdWithoutBlockPost()` V2 리팩토링
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: ⛏️ fix, 🔧 refactor

#90 [Fix/#79-NFE] 인증되지 않은 사용자가 접근할 경우 예외처리합니다
  src/main/java/com/apps/pochak/login/filter/JwtAuthorizationFilter.java
Labels: 🐛 bug, ⛏️ fix

#84 [refactor/#77-home-tab] 홈탭 게시물 조회 쿼리 리팩토링
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: 🐛 bug, ⛏️ fix, 🔧 refactor

#83 [refactor/#80-postrepo-find-upload-post] `findUploadPost()` 리팩토링
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: 🐛 bug, ⛏️ fix, 🔧 refactor

#89 [fix/#81-cloud-storage-migration] S3에서 GCS로 이동
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
  .gitignore
  build.gradle
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/image/CloudStorageConfig.java
  src/main/java/com/apps/pochak/global/image/CloudStorageService.java
  src/main/java/com/apps/pochak/global/image/DirName.java
  src/main/java/com/apps/pochak/global/s3/S3Config.java
  src/main/java/com/apps/pochak/global/s3/S3Service.java
  src/main/java/com/apps/pochak/login/service/OAuthService.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/service/PostService.java
Labels: 🛠️ enhancement, ⛏️ fix

#91 [Fix/#79-NFE-bug] LoginArgumentResolver에서 NFE 예외처리하기
  src/main/java/com/apps/pochak/login/filter/JwtAuthorizationFilter.java
  src/main/java/com/apps/pochak/login/util/LoginArgumentResolver.java
Labels: 🐛 bug, ⛏️ fix

#101 [fix/#100-json-file] JSON 키 파일 세팅 에러 수정
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
Labels: 🐛 bug, ⛏️ fix

#102 익명유저 인가 처리 에러 해결 / GCS 마이그레이션
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
  .gitignore
  build.gradle
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/TagAlarm.java
  src/main/java/com/apps/pochak/block/domain/Block.java
  src/main/java/com/apps/pochak/comment/domain/Comment.java
  src/main/java/com/apps/pochak/follow/domain/Follow.java
  src/main/java/com/apps/pochak/global/BaseEntity.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/image/CloudStorageConfig.java
  src/main/java/com/apps/pochak/global/image/CloudStorageService.java
  src/main/java/com/apps/pochak/global/image/DirName.java
  src/main/java/com/apps/pochak/global/s3/S3Config.java
  src/main/java/com/apps/pochak/global/s3/S3Service.java
  src/main/java/com/apps/pochak/like/domain/LikeEntity.java
  src/main/java/com/apps/pochak/login/filter/JwtAuthorizationFilter.java
  src/main/java/com/apps/pochak/login/service/OAuthService.java
  src/main/java/com/apps/pochak/login/util/LoginArgumentResolver.java
  src/main/java/com/apps/pochak/member/domain/Member.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/domain/Post.java
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/report/domain/Report.java
  src/main/java/com/apps/pochak/tag/domain/Tag.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: 📤 Release

#106 [Fix/#104-memories-npe] 추억페이지 null값으로 dto 리턴
  src/main/java/com/apps/pochak/memories/dto/MemoriesElement.java
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
Labels: ⛏️ fix

#105 [Refactor/#67-postrepo-querydsl] 메소드 순서 및 정리
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: 🔧 refactor

#98 [Refactor/#93-alarm-column] LikeAlarm 컬럼명 수정하기
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/LikeAlarmElement.java
Labels: 🔧 refactor

#110 [Refactor/#109-like-entity-column] LikeEntity 컬럼명 변경
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/service/LikeAlarmService.java
  src/main/java/com/apps/pochak/like/domain/LikeEntity.java
  src/main/java/com/apps/pochak/like/domain/repository/LikeRepository.java
  src/main/java/com/apps/pochak/like/service/LikeService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/main/java/com/apps/pochak/post/service/PostService.java
Labels: 🔧 refactor

#97 [refactor/#96-find-followers] 팔로워 조회 리팩토링
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/member/domain/repository/CustomMemberRepository.java
  src/main/java/com/apps/pochak/member/domain/repository/MemberCustomRepository.java
  src/main/java/com/apps/pochak/member/dto/response/MemberElement.java
  src/test/java/com/apps/pochak/global/TestQuerydslConfig.java
  src/test/java/com/apps/pochak/member/domain/repository/MemberCustomRepositoryTest.java
Labels: 🔧 refactor

#117 [fix/#78-alarm-query-update] 테스트 코드 수정
  src/test/java/com/apps/pochak/alarm/fixture/AlarmFixture.java
  src/test/java/com/apps/pochak/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/apps/pochak/follow/fixture/FollowFixture.java
  src/test/java/com/apps/pochak/global/TestQuerydslConfig.java
  src/test/java/com/apps/pochak/like/fixture/LikeFixture.java
  src/test/java/com/apps/pochak/member/domain/repository/MemberCustomRepositoryTest.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
  src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
  src/test/java/com/apps/pochak/tag/fixture/TagFixture.java
Labels: 🐛 bug

#111 [Refactor/#109-report-column] Report 컬럼명 변경
  src/main/java/com/apps/pochak/report/domain/Report.java
Labels: 🔧 refactor

#114 [Refactor/#108-sign-up-validation] 회원가입시 유저 데이터의 유효성을 검사합니다
  src/main/java/com/apps/pochak/login/dto/request/MemberInfoRequest.java
  src/main/java/com/apps/pochak/login/service/OAuthService.java
  src/main/java/com/apps/pochak/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/test/java/com/apps/pochak/login/controller/OAuthControllerTest.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
Labels: 🔧 refactor

#112 [fix/#107-update-api-docs] API 문서 자세한 설명 추가
  src/docs/asciidoc/profile.adoc
  src/test/java/com/apps/pochak/global/MockMultipartFileConverter.java
  src/test/java/com/apps/pochak/login/controller/OAuthControllerTest.java
  src/test/java/com/apps/pochak/member/controller/MemberControllerTest.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
Labels: 📄 docs
