Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2024-12, with the labels that each got.

#120 [Feat/#6-logging] API 요청 및 Exception에 관해 로그 쌓기
  .gitignore
  scripts/logtogcs.sh
  src/main/java/com/apps/pochak/PochakApplication.java
  src/main/java/com/apps/pochak/global/api_payload/exception/ExceptionAdvice.java
  src/main/java/com/apps/pochak/global/aspect/LogAspect.java
  src/main/java/com/apps/pochak/global/util/RequestInfo.java
  src/main/resources/application-PROD.properties
  src/main/resources/logback-spring.xml
Labels: 🛠️ enhancement

#131 [feat/#116-encrypt-secret-file] 키파일 github actions 에러 수정
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
Labels: 🐛 bug, ⛏️ fix

#137 [fix/#121-fcm-token-specify] FCM Token 지정 에러
  src/main/java/com/apps/pochak/fcm/service/FCMService.java
Labels: 🐛 bug, ⛏️ fix

#132 [feat/#128-alarm-dto-time] Alarm 조회 DTO 생성 시간 추가
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElement.java
  src/main/java/com/apps/pochak/global/BaseEntity.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
Labels: 🛠️ enhancement

#126 [refactor/#125-validate-post] 게시물 validation 리팩토링
  src/main/java/com/apps/pochak/global/annotation/ValidDuplicateList.java
  src/main/java/com/apps/pochak/global/annotation/ValidDuplicateListValidator.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
  src/main/java/com/apps/pochak/post/dto/response/PostDetailResponse.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
Labels: 🛠️ enhancement, 🔧 refactor

#138 [Fix/#6-logging] response가 String인 경우 CastException 발생 처리
  src/main/java/com/apps/pochak/global/aspect/LogAspect.java
Labels: 🐛 bug

#135 [feat/#134-memories-timeline] 추억페이지 response DTO 타임라인 추가
  src/main/java/com/apps/pochak/global/util/TimeUtil.java
  src/main/java/com/apps/pochak/memories/domain/MemoriesType.java
  src/main/java/com/apps/pochak/memories/dto/MemoriesElement.java
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
  src/main/java/com/apps/pochak/memories/service/MemoriesService.java
  src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
  src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
Labels: 🛠️ enhancement

#141 [fix/#47-refresh-token-npe] 토큰 NPE 핸들링
  src/main/java/com/apps/pochak/login/util/LoginArgumentResolver.java
Labels: 🐛 bug, ⛏️ fix

#147 [Feat/#129-getPostDetail-Datetime] 게시물 상세 조회 responseDto에 게시 날짜 및 시간 포함하기
  src/main/java/com/apps/pochak/post/dto/response/PostDetailResponse.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
Labels: 🛠️ enhancement, ⛏️ fix

#149 [Feat/#148-memories-post-date] 추억페이지 갤러리 조회시 게시 날짜 추가
  src/main/java/com/apps/pochak/post/dto/PostElement.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
Labels: 🛠️ enhancement

#152 [Fix/#151-memories-NPE] 추억페이지 조회시 null Tag 조회 막기, 타임라인 postOwner 추가 전달하기
  src/main/java/com/apps/pochak/memories/dto/TimeLineElement.java
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
Labels: 🐛 bug, ⛏️ fix

#144 [test/#142-alarm-service] 알람 테스트
  src/main/java/com/apps/pochak/alarm/controller/AlarmController.java
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElement.java
  src/main/java/com/apps/pochak/alarm/service/AlarmService.java
  src/main/java/com/apps/pochak/fcm/config/FCMConfig.java
  src/main/java/com/apps/pochak/follow/controller/FollowController.java
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/SuccessStatus.java
  src/main/java/com/apps/pochak/tag/controller/TagController.java
  src/main/java/com/apps/pochak/tag/service/TagService.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/alarm/service/AlarmServiceTest.java
  src/test/java/com/apps/pochak/alarm/service/CommentAlarmServiceTest.java
  src/test/java/com/apps/pochak/alarm/service/FollowAlarmServiceTest.java
  src/test/java/com/apps/pochak/alarm/service/LikeAlarmServiceTest.java
  src/test/java/com/apps/pochak/alarm/service/TagAlarmServiceTest.java
  src/test/java/com/apps/pochak/follow/controller/FollowControllerTest.java
  src/test/java/com/apps/pochak/global/ServiceTest.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
  src/test/java/com/apps/pochak/tag/controller/TagControllerTest.java
Labels: 🎯 test, 🔧 refactor

#140 [test/#136-post-service] PostService 테스트
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/global/BaseEntity.java
  src/test/java/com/apps/pochak/post/service/PostServiceTest.java
Labels: 🎯 test
