Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2024-09, with the labels that each got.

#50 [feature/#46-env-separation] Spring Profile을 사용한 Dev/Prod 설정 변경
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application.properties
  src/test/java/com/apps/pochak/PochakApplicationTests.java
  src/test/resources/application.properties
Labels: 🛠️ enhancement

#51 [feature/#44-discord-bot] 서버 에러 발생을 알리는 디스코드 봇
  build.gradle
  src/main/java/com/apps/pochak/PochakApplication.java
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElements.java
  src/main/java/com/apps/pochak/block/dto/response/BlockElements.java
  src/main/java/com/apps/pochak/comment/dto/response/CommentElements.java
  src/main/java/com/apps/pochak/comment/dto/response/ParentCommentElement.java
  src/main/java/com/apps/pochak/discord/client/DiscordClient.java
  src/main/java/com/apps/pochak/discord/dto/DiscordMessage.java
  src/main/java/com/apps/pochak/discord/service/DiscordService.java
  src/main/java/com/apps/pochak/global/annotation/ValidFile.java
  src/main/java/com/apps/pochak/global/annotation/ValidFileValidator.java
  src/main/java/com/apps/pochak/global/api_payload/exception/ExceptionAdvice.java
  src/main/java/com/apps/pochak/global/util/PageInfo.java
  src/main/java/com/apps/pochak/global/util/RequestInfo.java
  src/main/java/com/apps/pochak/login/dto/request/MemberInfoRequest.java
  src/main/java/com/apps/pochak/member/dto/response/MemberElements.java
  src/main/java/com/apps/pochak/member/dto/response/ProfileResponse.java
  src/main/java/com/apps/pochak/post/dto/PostElements.java
  src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
Labels: 🛠️ enhancement

#56 [feature/#55-github-actions] github actions 작업
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
  src/test/java/com/apps/pochak/global/ControllerTest.java
Labels: 🛠️ enhancement

#58 [feature/#57-convention] 깃허브 컨벤션
  .github/ISSUE_TEMPLATE/refactor_report.md
  .github/pull_request_template.md
  README.md
Labels: 🛠️ enhancement

#63 [fix/#62-key-files] Actions 키 파일 세팅 부분 수정
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
Labels: 🐛 bug, ⛏️ fix

#64 [fix/#49-apple-login] 로그인 리팩토링, 설정 변경
  .gitignore
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/config/RestTemplateConfig.java
  src/main/java/com/apps/pochak/login/client/AppleClient.java
  src/main/java/com/apps/pochak/login/client/GoogleClient.java
  src/main/java/com/apps/pochak/login/dto/apple/ApplePublicKey.java
  src/main/java/com/apps/pochak/login/dto/apple/ApplePublicKeyResponse.java
  src/main/java/com/apps/pochak/login/service/AppleOAuthService.java
  src/main/java/com/apps/pochak/login/service/GoogleOAuthService.java
  src/main/java/com/apps/pochak/login/util/ApplePublicKeyGenerator.java
Labels: ⛏️ fix, 🔧 refactor

#71 [refactor/#70-jpa-auditing-setting] JPA Auditing 설정 옮기기
  src/main/java/com/apps/pochak/PochakApplication.java
  src/main/java/com/apps/pochak/global/config/JpaAuditingConfig.java
Labels: 🔧 refactor

#60 [feature/#54-memories] 추억 페이지 프리뷰 API
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/memories.adoc
  src/main/java/com/apps/pochak/global/BaseEntity.java
  src/main/java/com/apps/pochak/global/util/PageUtil.java
  src/main/java/com/apps/pochak/memories/controller/MemoriesController.java
  src/main/java/com/apps/pochak/memories/dto/MemoriesElement.java
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPostResponse.java
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
  src/main/java/com/apps/pochak/memories/service/MemoriesService.java
  src/main/java/com/apps/pochak/post/dto/PostElement.java
  src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
  src/test/java/com/apps/pochak/follow/fixture/FollowFixture.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
  src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
  src/test/java/com/apps/pochak/tag/fixture/TagFixture.java
Labels: 🛠️ enhancement

#72 [Fix/#53-alarm-db-update] Alarm 엔티티 구조 변경
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/TagAlarm.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/CommentAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/FollowAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/LikeAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/TagApprovalAlarmElement.java
Labels: ⛏️ fix

#68 [refactor/#67-postrepo-querydsl] PostCustomRepository - `findPostByIdWithoutBlockPost()` 리팩토링
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/apps/pochak/comment/service/CommentService.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/config/QuerydslConfig.java
  src/main/java/com/apps/pochak/like/service/LikeService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/report/service/ReportService.java
  src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/alarm/fixture/AlarmFixture.java
  src/test/java/com/apps/pochak/block/controller/BlockControllerTest.java
  src/test/java/com/apps/pochak/block/fixture/BlockFixture.java
  src/test/java/com/apps/pochak/comment/controller/CommentControllerTest.java
  src/test/java/com/apps/pochak/comment/fixture/CommentFixture.java
  src/test/java/com/apps/pochak/follow/controller/FollowControllerTest.java
  src/test/java/com/apps/pochak/follow/fixture/FollowFixture.java
  src/test/java/com/apps/pochak/global/TestQuerydslConfig.java
  src/test/java/com/apps/pochak/like/controller/LikeControllerTest.java
  src/test/java/com/apps/pochak/like/fixture/LikeFixture.java
  src/test/java/com/apps/pochak/login/controller/OAuthControllerTest.java
  src/test/java/com/apps/pochak/member/controller/MemberControllerTest.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
  src/test/java/com/apps/pochak/report/controller/ReportControllerTest.java
  src/test/java/com/apps/pochak/tag/controller/TagControllerTest.java
  src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
  src/test/java/com/apps/pochak/tag/fixture/TagFixture.java
Labels: 🔧 refactor
