Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2024-07, with the labels that each got.

#14 [feat/2-profile-update] 프로필 수정 API
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/s3/S3Service.java
  src/main/java/com/apps/pochak/member/controller/MemberController.java
  src/main/java/com/apps/pochak/member/domain/Member.java
  src/main/java/com/apps/pochak/member/domain/repository/MemberRepository.java
  src/main/java/com/apps/pochak/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/apps/pochak/member/dto/response/ProfileUpdateResponse.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
Labels: 🛠️ enhancement

#24 [fix/9-alarm-creation-error] 알람 생성 오류
  src/docs/asciidoc/alarm.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/tag.adoc
  src/main/java/com/apps/pochak/alarm/controller/AlarmController.java
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/TagAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElements.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/CommentAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/FollowAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/LikeAlarmElement.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/TagApprovalAlarmElement.java
  src/main/java/com/apps/pochak/alarm/service/AlarmService.java
  src/main/java/com/apps/pochak/comment/service/CommentService.java
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/api_payload/exception/ExceptionAdvice.java
  src/main/java/com/apps/pochak/like/service/LikeService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/main/java/com/apps/pochak/post/dto/response/PostPreviewResponse.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/tag/dto/response/TagElement.java
  src/main/java/com/apps/pochak/tag/service/TagService.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/tag/controller/TagControllerTest.java
Labels: 🐛 bug, ⛏️ fix

#25 [fix/21-social-login] 애플로그인 리팩토링,
  src/main/java/com/apps/pochak/PochakApplication.java
  src/main/java/com/apps/pochak/alarm/service/AlarmService.java
  src/main/java/com/apps/pochak/block/service/BlockService.java
  src/main/java/com/apps/pochak/comment/service/CommentService.java
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/global/api_payload/exception/handler/AuthenticationException.java
  src/main/java/com/apps/pochak/like/service/LikeService.java
  src/main/java/com/apps/pochak/login/config/SecurityConfig.java
  src/main/java/com/apps/pochak/login/controller/OAuthController.java
  src/main/java/com/apps/pochak/login/dto/apple/AppleTokenResponse.java
  src/main/java/com/apps/pochak/login/dto/apple/key/ApplePublicKey.java
  src/main/java/com/apps/pochak/login/dto/apple/key/ApplePublicKeyResponse.java
  src/main/java/com/apps/pochak/login/dto/google/GoogleMemberResponse.java
  src/main/java/com/apps/pochak/login/dto/google/GoogleTokenResponse.java
  src/main/java/com/apps/pochak/login/dto/request/UserInfoRequest.java
  src/main/java/com/apps/pochak/login/dto/response/AccessTokenResponse.java
  src/main/java/com/apps/pochak/login/dto/response/ApplePublicKeyResponse.java
  src/main/java/com/apps/pochak/login/dto/response/GoogleUserResponse.java
  src/main/java/com/apps/pochak/login/dto/response/OAuthResponse.java
  src/main/java/com/apps/pochak/login/filter/JwtAuthorizationFilter.java
  src/main/java/com/apps/pochak/login/provider/JwtProvider.java
  src/main/java/com/apps/pochak/login/service/AppleOAuthService.java
  src/main/java/com/apps/pochak/login/service/GoogleOAuthService.java
  src/main/java/com/apps/pochak/login/service/OAuthService.java
  src/main/java/com/apps/pochak/login/util/ApplePublicKeyGenerator.java
  src/main/java/com/apps/pochak/login/util/JwtHeaderUtil.java
  src/main/java/com/apps/pochak/login/util/JwtValidator.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/report/service/ReportService.java
  src/main/java/com/apps/pochak/tag/service/TagService.java
Labels: ⛏️ fix

#27 [feat/26-get-tagged-member] 태그된 유저 조회, 태그 수 제한
  src/main/java/com/apps/pochak/block/dto/response/BlockElement.java
  src/main/java/com/apps/pochak/comment/dto/response/CommentElement.java
  src/main/java/com/apps/pochak/comment/dto/response/ParentCommentElement.java
  src/main/java/com/apps/pochak/global/api_payload/code/status/ErrorStatus.java
  src/main/java/com/apps/pochak/like/domain/repository/LikeRepository.java
  src/main/java/com/apps/pochak/like/dto/response/LikeElement.java
  src/main/java/com/apps/pochak/login/provider/JwtProvider.java
  src/main/java/com/apps/pochak/post/dto/response/PostDetailResponse.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/tag/dto/response/TagElement.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/comment/controller/CommentControllerTest.java
  src/test/java/com/apps/pochak/like/controller/LikeControllerTest.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
Labels: 🛠️ enhancement, ⛏️ fix

#28 [fix/9-save-alarm-error] 알람 생성 에러 고치기
  src/docs/asciidoc/alarm.adoc
  src/main/java/com/apps/pochak/alarm/domain/Alarm.java
  src/main/java/com/apps/pochak/alarm/domain/AlarmType.java
  src/main/java/com/apps/pochak/alarm/domain/CommentAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/FollowAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/LikeAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/TagAlarm.java
  src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
  src/main/java/com/apps/pochak/alarm/service/CommentAlarmService.java
  src/main/java/com/apps/pochak/alarm/service/FollowAlarmService.java
  src/main/java/com/apps/pochak/alarm/service/LikeAlarmService.java
  src/main/java/com/apps/pochak/alarm/service/TagAlarmService.java
  src/main/java/com/apps/pochak/comment/domain/repository/CommentRepository.java
  src/main/java/com/apps/pochak/comment/service/CommentService.java
  src/main/java/com/apps/pochak/follow/controller/FollowController.java
  src/main/java/com/apps/pochak/follow/service/FollowService.java
  src/main/java/com/apps/pochak/like/domain/repository/LikeRepository.java
  src/main/java/com/apps/pochak/like/service/LikeService.java
  src/main/java/com/apps/pochak/post/domain/Post.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
  src/main/java/com/apps/pochak/tag/service/TagService.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/comment/controller/CommentControllerTest.java
Labels: ⛏️ fix

#30 [FEAT/29-caching] 이미지 로딩 속도 개선
  src/main/java/com/apps/pochak/global/s3/S3Service.java
Labels: 🛠️ enhancement
