Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2025-02, with the labels that each got.

#143 [Feat/#130-alarm-auto-delete] 만료 알람 자동 삭제
  src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
  src/main/java/com/apps/pochak/alarm/service/AlarmDeletionScheduler.java
  src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
Labels: 🛠️ enhancement

#163 [test/#155-follow-test] 팔로우 서비스 테스트
  src/test/java/com/apps/pochak/follow/service/FollowServiceTest.java
Labels: 🎯 test

#167 [test/#166-tag-service] 태그 서비스 테스트
  src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
  src/test/java/com/apps/pochak/tag/service/TagServiceTest.java
Labels: 🎯 test

#165 [test/#164-like-service] 좋아요 서비스 테스트
  src/test/java/com/apps/pochak/like/service/LikeServiceTest.java
Labels: 🎯 test

#176 [fix/#175-signup-image] 회원가입 완료 후 회원 프로필 이미지 전달
  src/main/java/com/apps/pochak/login/dto/response/OAuthMemberResponse.java
  src/test/java/com/apps/pochak/login/controller/OAuthControllerTest.java
Labels: ⛏️ fix

#174 [Feat/#76-jacoco-sonar] 자코코&소나클라우드 도입
  .github/workflows/pr-sonarcloud-and-coverage.yml
  build.gradle
  src/test/java/com/apps/pochak/alarm/repository/AlarmRepositoryTest.java
Labels: 🛠️ enhancement

#178 [HotFix/#76-jacoco-sonar] 빌드 실패, 의존성 설정
  build.gradle
Labels: ⛏️ fix

#162 [Test/#156-comment-service] 댓글 서비스 테스트
  src/main/java/com/apps/pochak/comment/domain/repository/CommentRepository.java
  src/main/java/com/apps/pochak/comment/dto/response/CommentElements.java
  src/main/java/com/apps/pochak/comment/dto/response/ParentCommentElement.java
  src/main/java/com/apps/pochak/comment/service/CommentService.java
  src/test/java/com/apps/pochak/comment/controller/CommentControllerTest.java
  src/test/java/com/apps/pochak/comment/domain/repository/CommentRepositoryTest.java
  src/test/java/com/apps/pochak/comment/fixture/CommentFixture.java
  src/test/java/com/apps/pochak/comment/service/CommentServiceTest.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
Labels: 🎯 test

#158 [Refactor/#157-comment-repository] 차단 회원의 자식 댓글 조회 막기
  src/main/java/com/apps/pochak/comment/controller/CommentController.java
  src/main/java/com/apps/pochak/comment/domain/repository/CommentRepository.java
  src/main/java/com/apps/pochak/comment/dto/response/CommentElements.java
  src/main/java/com/apps/pochak/comment/dto/response/ParentCommentElement.java
  src/main/java/com/apps/pochak/global/Constant.java
  src/test/java/com/apps/pochak/comment/domain/repository/CommentRepositoryTest.java
  src/test/java/com/apps/pochak/comment/service/CommentServiceTest.java
Labels: 🛠️ enhancement, 🎯 test, 🔧 refactor

#169 [Fix/#108-profile-update-validation] 프로필 수정시 유효성 검사를 한다
  src/main/java/com/apps/pochak/member/controller/MemberController.java
  src/main/java/com/apps/pochak/member/dto/request/ProfileUpdateRequest.java
  src/test/java/com/apps/pochak/member/controller/MemberControllerTest.java
  src/test/java/com/apps/pochak/member/fixture/MemberFixture.java
Labels: ⛏️ fix, 🎯 test

#172 [Test/#170-memories-service] 추억페이지 서비스 테스트
  src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
  src/main/java/com/apps/pochak/memories/service/MemoriesService.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
  src/test/java/com/apps/pochak/memories/service/MemoriesServiceTest.java
Labels: 🎯 test

#183 [feat/#177-moment-post] 순간포착 게시물 업로드
  src/docs/asciidoc/alarm.adoc
  src/docs/asciidoc/post.adoc
  src/docs/asciidoc/tag.adoc
  src/main/java/com/apps/pochak/alarm/domain/AlarmType.java
  src/main/java/com/apps/pochak/alarm/domain/PostAlarm.java
  src/main/java/com/apps/pochak/alarm/dto/response/AlarmElements.java
  src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/PostAlarmElement.java
  src/main/java/com/apps/pochak/alarm/service/PostAlarmService.java
  src/main/java/com/apps/pochak/follow/domain/repository/FollowRepository.java
  src/main/java/com/apps/pochak/global/Constant.java
  src/main/java/com/apps/pochak/global/config/AsyncConfig.java
  src/main/java/com/apps/pochak/post/domain/Post.java
  src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
  src/main/java/com/apps/pochak/post/service/PostImageDeletionScheduler.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/main/java/com/apps/pochak/tag/service/TagService.java
  src/test/java/com/apps/pochak/alarm/controller/AlarmControllerTest.java
  src/test/java/com/apps/pochak/alarm/fixture/AlarmFixture.java
  src/test/java/com/apps/pochak/alarm/service/PostAlarmServiceTest.java
  src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
  src/test/java/com/apps/pochak/post/service/PostImageDeletionSchedulerTest.java
Labels: 🛠️ enhancement

#188 [refactor/#187-image-url] 이미지 파일 저장방식 변경
  src/main/java/com/apps/pochak/global/image/CloudStorageService.java
  src/main/java/com/apps/pochak/login/dto/request/MemberInfoRequest.java
  src/main/java/com/apps/pochak/login/service/OAuthService.java
  src/main/java/com/apps/pochak/member/domain/Member.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/domain/Post.java
  src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
  src/main/java/com/apps/pochak/post/service/PostService.java
  src/test/java/com/apps/pochak/global/ServiceTest.java
Labels: ⛏️ fix, 🔧 refactor

#191 [hotfix/#177-npe-error] 게시물 업로드 과정에서 NPE 수정
  src/main/java/com/apps/pochak/global/annotation/ValidDuplicateListValidator.java
  src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
Labels: ⛏️ fix

#192 [Chore/#76-jacoco-sonar] SonarQuber 커버리지 제외 대상 추가
  build.gradle
Labels: ⛏️ fix

#197 [feat/#55-githubactions] github actions 브랜치 변경
  .github/workflows/dev-server.yml
  .github/workflows/prod-server.yml
Labels: ⛏️ fix
