Repository SMWU-POCHAK/POCHAK-Server, pull requests merged in 2025-01, with the labels that each got.

#150 [Feat/#122-savePost-image-delete] 게시물 업로드 에러 발생시 업로드된 이미지 삭제하기
  src/main/java/com/apps/pochak/global/image/CloudStorageService.java
  src/main/java/com/apps/pochak/post/service/PostService.java
Labels: 🐛 bug, ⛏️ fix

#159 [test/#154-block-service] 차단 테스트
  src/main/java/com/apps/pochak/block/service/BlockService.java
  src/main/java/com/apps/pochak/follow/domain/repository/FollowRepository.java
  src/main/java/com/apps/pochak/like/domain/repository/LikeRepository.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/test/java/com/apps/pochak/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/apps/pochak/block/service/BlockServiceTest.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
  src/test/java/com/apps/pochak/post/fixture/PostFixture.java
  src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
Labels: 🐛 bug, 🎯 test

#153 [feat/#146-delete-post-image] 게시물 이미지 삭제 스케줄러
  build.gradle
  src/main/java/com/apps/pochak/global/config/ClockConfig.java
  src/main/java/com/apps/pochak/global/image/CloudStorageService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/main/java/com/apps/pochak/post/service/PostImageDeletionScheduler.java
  src/test/java/com/apps/pochak/post/service/PostImageDeletionSchedulerTest.java
Labels: 🛠️ enhancement

#161 [Feat/#160-memories-getF4FStatus-api] 추억페이지 맞팔 상태 조회
  src/docs/asciidoc/memories.adoc
  src/main/java/com/apps/pochak/member/dto/response/ProfileResponse.java
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/memories/controller/MemoriesController.java
  src/main/java/com/apps/pochak/memories/service/MemoriesService.java
  src/test/java/com/apps/pochak/member/controller/MemberControllerTest.java
  src/test/java/com/apps/pochak/memories/controller/MemoriesControllerTest.java
Labels: 🛠️ enhancement

#99 [Refactor/#94-findTaggedPost()] `findTaggedPost()` QueryDSL로 리팩토링
  src/main/java/com/apps/pochak/member/service/MemberService.java
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
  src/main/java/com/apps/pochak/post/domain/repository/PostRepository.java
  src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
Labels: 🔧 refactor

#168 [hotfix/#94-tagged-post] POCHAKED 탭 조회 정렬 조건 수정
  src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
Labels: ⛏️ fix
